version: '3'
services:
  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - SECRET_KEY=your_production_secret_key
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db:5432/dollardollar
      - DEVELOPMENT_MODE=False
      - DISABLE_SIGNUPS=True  # Set to True to disable signups
    depends_on:
      db:
        condition: service_healthy

    command: gunicorn --bind 0.0.0.0:5001 app:app

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dollardollar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5

volumes:
  postgres_data: